import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "@/components/ModeToggle";
import Link from "next/link";
import { Search } from "@/components/Search";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "WatchNext | Brohud",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="p-4 flex gap-10 items-center font-bold">
              <ModeToggle />
              <Link href="/videos" className="text-3xl  dark:text-fuchsia-500 text-blue-500">
                <h1>WatchNext</h1>
                </Link>
              </div>
            <div className="p-4">{children}</div>
          </ThemeProvider> 
      </body>
    </html>
  );
}
